import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/keybinding.toml.toml",
]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]
# args = ["-l"]

[window]
dimensions = { columns = 80, lines = 24 }
position = { x = 0, y = 0 }
decorations = "Buttonless"
# (macos only)
option_as_alt = "Both"

[font]
normal = { family = "IosevkaTerm NF", style = "Regular" }
size = 19.5

[cursor]
style = { shape = "Block" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "Insert", mods = "Control", action = "Copy" },
  { key = "Insert", mods = "Shift", action = "Paste" },
]
