[general]
import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/keybinding.toml",
]

[window]
dimensions = { columns = 80, lines = 24 }
decorations = "Buttonless"                # (macOS only)
decorations_theme_variant = "Dark"
option_as_alt = "Both"                    # (macOS only)

[font]
normal = { family = "IosevkaTerm NF", style = "Regular" }
size = 19.5

[cursor]
style = { shape = "Block" }

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]
# args = ["-l"]

[mouse]
hide_when_typing = true
