# https://github.com/jonniek/mpv-playlistmanager
# Shift+ENTER show playlist

# https://github.com/Ajatt-Tools/videoclip
# c videoclip menu open

RIGHT      seek 2
LEFT       seek -2
UP         add  volume 2
DOWN       add  volume -2
WHEEL_UP   add  volume 2
WHEEL_DOWN add  volume -2


; script-message osc-visibility auto
: script-message osc-visibility never

### ignore

# playback speed
[ ignore # decrease
] ignore # increase
{ ignore # halve current
} ignore # double current
BS ignore # reset
Shift+BS ignore # undo last seek
Shift+Ctrl+BS ignore

# playlist
# < playlist-prev                        # skip to the previous file
# > playlist-next                        # skip to the next file
ENTER ignore # forward
p ignore # toggle pause

# volume
/ ignore # decrease
* ignore # increase
9 ignore # decrease
0 ignore # increase
# m ignore # mute

# cycle tracks
_ ignore # video 
# %n%# ignore # audio
E ignore # editions
# f ignore # fullscreen

T ignore # toggle stay on top

# panscan
w ignore # decrease
W ignore # increase
e ignore

# show progression bar
o ignore
P ignore
O ignore # toggle OSD states

# subtitle
v ignore # toggle subtitle
j ignore # cycle
J ignore # cycle
z ignore # decrease adjust delay
Z ignore # increase adjust delay 

# loop
l ignore # set/clear A-B loop
L ignore # toggle infinite

# audio delay
Ctrl++ ignore           # change audio/video sync by delaying the audio
Ctrl+- ignore          # change audio/video sync by shifting the audio earlier

#subtitle fonts size
Shift+g ignore 
Shift+f ignore 

u ignore
V ignore # toggle subtitle VSFiter
r ignore # move subtitle
R ignore # move subtitle

s ignore # screenshot, wihout subtitles
Ctrl+s ignore # screenshot, as the window

PGUP ignore # see
PGDWN ignore
Shift+PGUP ignore # see
Shift+PGDWN ignore

b ignore # toggle debanding
d ignore # cycle deinterlacing filter
A ignore # cycle aspect ratio override

Ctrl+h ignore # toggle hardware video decoding

# move the video rectangle (panning)
Alt+left  ignore
Alt+right ignore
Alt+up    ignore
Alt+down  ignore

# ZOOM
Alt++     ignore
#ZOOMIN    ignore
Alt+-     ignore
#ZOOMOUT   ignore

Alt+BS ignore

F8 ignore
F9 ignore

i ignore # show/toggle overaly display statistics
I ignore # show/toggle overaly display statistics

DEL ignore # cycle OSC visibility
` ignore # show console 

# display adjust
1 ignore # contrast
2 ignore # contrast
3 ignore # brightness
4 ignore # brightness
5 ignore # gamma
6 ignore # gamma
7 ignore # saturation
8 ignore # saturation

# resize window
Alt+0 ignore # half
Alt+1 ignore # original
Alt+2 ignore # double
