volume=0

osd-font-size=40
osd-on-seek=bar

osd-bar-align-y=0.93
osd-bar-w=67
osd-bar-h=1.5

osd-back-color=0/0/0/0.33
osd-border-size=0

geometry=70%:70%
autofit-larger=70%:70%

save-position-on-quit

script-opts=osc-visibility=always

keep-open=always
